FROM python:3.13-slim

WORKDIR /app

RUN pip install --upgrade pip && pip install "poetry==2.1.0"

COPY pyproject.toml ./

# Install project dependencies (avoid creating a virtual environment and installing development dependencies)
RUN poetry config virtualenvs.create false && poetry install --no-root

COPY . .