#!/bin/bash

set -euxo pipefail

PATH_DATA=$1
SCHEMA_NAME=$2
TABLE_NAME=$3

echo "PATH_DATA: ${PATH_DATA}"
echo "SCHEMA_NAME: ${SCHEMA_NAME}"
echo "TABLE_NAME: ${TABLE_NAME}"
echo "POSTGRES_USER: ${POSTGRES_USER}"
echo "POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}"
echo "POSTGRES_HOST: ${POSTGRES_HOST}"
echo "POSTGRES_PORT: ${POSTGRES_PORT}"
echo "POSTGRES_DB_MAIN: ${POSTGRES_DB_MAIN}"

echo "Dropping ${SCHEMA_NAME}.${TABLE_NAME}"
PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB_MAIN}"  -c "DROP TABLE IF EXISTS ${SCHEMA_NAME}.${TABLE_NAME};"

for i in 2 4 8 16;
do
  echo "Dropping ${SCHEMA_NAME}.o_${i}_${TABLE_NAME}"
  PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB_MAIN}"  -c "DROP TABLE IF EXISTS ${SCHEMA_NAME}.o_${i}_${TABLE_NAME};"
done

echo "Loading ${SCHEMA_NAME}.${TABLE_NAME}"

raster2pgsql -c -C -s 54009 -t 256x256 -Y 1000 -l 2,4,8,16 "${PATH_DATA}" "${SCHEMA_NAME}.${TABLE_NAME}" | PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB_MAIN}"

echo "Completed loading ${SCHEMA_NAME}.${TABLE_NAME}"